### ISSUE TITLE
[3090 rtx] Very slow training on resnet with 1 block

### ISSUE THREAD

**Issue by HadiSDev** [werner-duvaud/muzero-general#150] opened 2021-04-18 13:36 UTC
I tried to train a game with resnet as my network. Was extremely slow on a computer with 5950x and 3090 rtx. (like 1 step per 2-3 seconds). I then tried to decrease the number of resblocks to 1. It helped a bit but still very slow. I then tried to use a fullyconnected network and everything was running very fast and smooth. 

Of my understanding, 3090 is perfectly capable of running a resnet with many blocks. These are the torch packages that I use:
torch==1.8.1+cu111
torchvision==0.9.1+cu111
torchaudio===0.8.1

**Comment by fbondeaux** [comment] 2021-04-21 12:18
Which game?

**Comment by HadiSDev** [comment] 2021-04-21 12:21
I tried the Atari one: https://github.com/werner-duvaud/muzero-general/blob/master/games/atari.py.

I just reduced the number of workers to something testable.

**Comment by werner-duvaud** [comment] 2021-04-25 12:35
Hi,

For a step, MuZero must evaluate a tree of future steps. It takes a long time to train, by default inference is done on the CPU, there is an option to do self play on GPU, it should speed up `self_play_on_gpu=True`.
Also you can reduce the number of `num_simulations` (number of nodes in the MCTS) to speed up.

**Comment by kevaday** [comment] 2021-05-10 13:46
I'm having this same issue and selfplay_on_gpu only slows down the self play process even further. This is related to an issue that I have opened: #159

**Comment by ahainaut** [comment] 2022-03-05 13:14
Hello,
Thank you for reporting the issue, closing this one since it is a duplicate of #159.

**Closed by ahainaut** 2022-03-05 13:14 UTC
